package juy.project.euler;

/**
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued term
 * 
 * </p>
 * 
 * @author juy
 *
 */
public class Problem2 {

	public static void main(String[] args) {
		int limit = 4000000;

		int sum = 0;
		int current = 0;
		int t1 = 1;
		int t2 = 2;
		while (current < limit) {
			current = t1 + t2;
			if (current % 2 == 0) {
				sum = sum + current;
			}
			t1 = t2;
			t2 = current;
		}
		System.out.println(sum + 2);
	}

}
